
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DATABASE_TO_UPPER=FALSE;


  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true